export const foodDishes = [
  "Spaghetti Carbonara",
  "Beef Stroganoff",
  "Chicken Tikka Masala",
  "Pad Thai",
  "Margherita Pizza",
  "Ratatouille",
  "Sushi Rolls",
  "Biryani",
  "Chicken Alfredo",
  "Moussaka",
  "Falafel",
  "Tacos",
  "Clam Chowder",
  "Lobster Bisque",
  "Hamburger",
  "Caesar Salad",
  "Eggplant Parmesan",
  "French Onion Soup",
  "Chicken Noodle Soup",
  "Beef Tacos",
  "Vegan Burrito",
  "Shrimp Scampi",
  "Mushroom Risotto",
  "Butter Chicken",
  "Pho",
  "Kimchi Fried Rice",
  "Shakshuka",
  "Stuffed Bell Peppers",
  "Pulled Pork Sandwich",
  "Beef Wellington",
  "Chicken Quesadilla",
  "Vegetable Stir Fry",
  "Grilled Cheese Sandwich",
  "BBQ Ribs",
  "Lasagna",
  "Lamb Kebabs",
  "Paella",
  "Crab Cakes",
  "Peking Duck",
  "Fettuccine Alfredo",
  "Fish and Chips",
  "Greek Salad",
  "Ramen",
  "Beef Bourguignon",
  "Pork Schnitzel",
  "Gumbo",
  "Shepherd's Pie",
  "Macaroni and Cheese",
  "Chicken Pot Pie",
  "Mango Sticky Rice",
  "Chocolate Lava Cake",
  "Tuna Tartare",
  "Salmon Teriyaki",
  "Ceviche",
  "Bruschetta",
  "Chicken Parmesan",
  "Lentil Soup",
  "Potato Leek Soup",
  "Steak Frites",
  "Omelette",
  "Vegetarian Chili",
  "Quiche Lorraine",
  "Shrimp Tacos",
  "Chicken Wings",
  "Stuffed Mushrooms",
  "Bacon Wrapped Dates",
  "Caprese Salad",
  "Banh Mi Sandwich",
  "Pasta Primavera",
  "Chicken Fried Rice",
  "Vegetable Curry",
  "Seafood Paella",
  "Corned Beef and Cabbage",
  "Pad See Ew",
  "Grilled Salmon",
  "Meatball Sub",
  "Gnocchi",
  "Chili Con Carne",
  "Lobster Roll",
  "Chicken Shawarma",
  "Crème Brûlée",
  "Panna Cotta",
  "Pesto Pasta",
  "Fajitas",
  "Roast Chicken",
  "Jambalaya",
  "Baked Ziti",
  "Tom Yum Soup",
  "Spring Rolls",
  "Spinach and Artichoke Dip",
  "Miso Soup",
  "Bangers and Mash",
  "Chicken Satay",
  "Samosas",
  "Garlic Bread",
  "Churros",
  "Pumpkin Pie",
  "Tiramisu",
  "Baklava",
  "Croque Monsieur",
  "Poutine"
];


export const ingredients = [
  "Salt", "Pepper", "Olive Oil", "Garlic", "Onion", "Tomato", "Lemon", "Chicken Breast", "Ground Beef", "Basil",
  "Parsley", "Thyme", "Rosemary", "Cilantro", "Oregano", "Bay Leaf", "Sage", "Chili Powder", "Paprika", "Cumin",
  "Turmeric", "Coriander", "Ginger", "Soy Sauce", "Worcestershire Sauce", "Balsamic Vinegar", "Red Wine Vinegar",
  "White Wine Vinegar", "Apple Cider Vinegar", "Rice Vinegar", "Honey", "Brown Sugar", "White Sugar", "Maple Syrup",
  "Flour", "Cornstarch", "Baking Powder", "Baking Soda", "Yeast", "Cocoa Powder", "Vanilla Extract", "Almond Extract",
  "Almonds", "Walnuts", "Pecans", "Cashews", "Peanuts", "Peanut Butter", "Almond Butter", "Coconut Oil", "Butter",
  "Milk", "Heavy Cream", "Sour Cream", "Greek Yogurt", "Cheddar Cheese", "Mozzarella Cheese", "Parmesan Cheese",
  "Feta Cheese", "Goat Cheese", "Blue Cheese", "Brie Cheese", "Cream Cheese", "Eggs", "Bread", "Rice", "Pasta",
  "Quinoa", "Couscous", "Barley", "Farro", "Lentils", "Black Beans", "Chickpeas", "Kidney Beans", "Pinto Beans",
  "Tofu", "Tempeh", "Seitan", "Mushrooms", "Bell Peppers", "Carrots", "Celery", "Cucumber", "Zucchini", "Eggplant",
  "Broccoli", "Cauliflower", "Spinach", "Kale", "Lettuce", "Arugula", "Mixed Greens", "Potatoes", "Sweet Potatoes",
  "Butternut Squash", "Pumpkin", "Acorn Squash", "Spaghetti Squash", "Corn", "Green Beans", "Peas", "Asparagus",
  "Artichokes", "Beets", "Radishes", "Turnips", "Brussels Sprouts", "Leeks", "Scallions", "Chives", "Bok Choy",
  "Napa Cabbage", "Red Cabbage", "Savoy Cabbage", "Caraway Seeds", "Fennel Seeds", "Sesame Seeds", "Chia Seeds",
  "Flax Seeds", "Sunflower Seeds", "Pumpkin Seeds", "Dried Cranberries", "Raisins", "Dried Apricots", "Dried Figs",
  "Dates", "Prunes", "Dried Mango", "Dried Pineapple", "Canned Tomatoes", "Tomato Paste", "Tomato Sauce",
  "Crushed Tomatoes", "Sun-Dried Tomatoes", "Chicken Broth", "Beef Broth", "Vegetable Broth", "Fish Sauce",
  "Anchovies", "Capers", "Olives", "Pickles", "Jalapenos", "Hot Sauce", "Sriracha", "Coconut Milk", "Coconut Cream",
  "Shredded Coconut", "Pineapple", "Mango", "Banana", "Apple", "Orange", "Lime", "Grapefruit", "Strawberries",
  "Blueberries", "Raspberries", "Blackberries", "Cherries", "Grapes", "Pears", "Peaches", "Plums", "Nectarines",
  "Kiwi", "Papaya", "Watermelon", "Cantaloupe", "Honeydew", "Avocado", "Lettuce", "Romaine", "Iceberg Lettuce",
  "Butter Lettuce", "Endive", "Radicchio", "Watercress", "Alfalfa Sprouts", "Bean Sprouts", "Bamboo Shoots",
  "Water Chestnuts", "Snow Peas", "Snap Peas", "Okra", "Fennel", "Garlic Powder", "Onion Powder", "Mustard",
  "Dijon Mustard", "Whole Grain Mustard", "Yellow Mustard", "Horseradish", "Mayonnaise", "Ketchup", "BBQ Sauce",
  "Ranch Dressing", "Caesar Dressing", "Italian Dressing", "Tahini", "Hummus", "Salsa", "Guacamole", "Pesto",
  "Marinara Sauce", "Soy Milk", "Almond Milk", "Oat Milk", "Coconut Milk", "Rice Milk", "Butter", "Ghee",
  "Margarine", "Lard", "Shortening", "Chocolate Chips", "White Chocolate", "Dark Chocolate", "Milk Chocolate",
  "Caramel", "Marshmallows"
];

export const recipeTags = [
  "Italian", "Mexican", "Chinese", "Indian", "American", "Thai", "French", "Japanese", "Mediterranean", "Greek",
  "Vegan", "Vegetarian", "Gluten-Free", "Low Carb", "High Protein", "Dairy-Free", "Nut-Free", "Soy-Free", "Paleo",
  "Keto", "Whole30", "Appetizer", "Main Course", "Dessert", "Snack", "Breakfast", "Lunch", "Dinner", "Under 30 Minutes", "Low Calories"
];
